### ISSUE TITLE
Repo Name!

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUHome-API#1]
Currently, we have some choices:
- CAPUHome
- CAPULife

Any other suggestions? Or which one do you vote for?

We need your voice!

**Comment by zhzhzoo** [comment]
CAPULeben ~

**Comment by zhzhzoo** [comment]
CAPUVie ~

**Comment by zhzhzoo** [comment]
CAPUせいかつ ~

**Comment by huxuan** [comment]
@zhzhzoo 敢不敢给点注（jie）释

**Comment by zhzhzoo** [comment]
解释：都是 CAPULife

**Comment by huxuan** [comment]
还以为是什么别的新点子呢……Home和Life比较而言，我觉得Home更符合协会的属性，团队梦想爱嘛~23333

**Comment by JeldorPKU** [comment]
我觉得这个issue可以关了，名字就这么定了吧大家有意见吗～（我要来试试群 at）
@CAPU-ENG/developers

**Comment by zhzhzoo** [comment]
没意见 @CAPU-ENG/developers

**Comment by huxuan** [comment]
+1 for close

**Comment by JeldorPKU** [comment]
那这个Repo的名字就这样定了～
