### ISSUE TITLE
新旧 tid 的对应关系

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/CAPUHome-API#23]
众所周知，旧 tid 是每个版面单独排的，而新 tid 是所有 thread 放在一起排的。如果直接把旧 tid 复制到新的 tid 里，那就肯定会有两个不同 thread 的 tid 一样的情况。为了解决这个问题，我们要想个办法给旧的 thread 们重新编制一套 tid，使得任两个 thread 的 tid 不同。

我有两个方案：
1. 每个 thread 随便给一个 tid，然后在某处记录下这个 thread 的旧 tid；
2. 每个 thread 的新 tid ＝ 旧 tid + bid \* 20000。（因为水版帖子最多，快 19000 了）

然后大家兹瓷哪个呢？或者有别的也可以～

**Comment by JeldorPKU** [comment]
能不能依次记录啊，按`bid` `tid` 的优先级排序，再重新编号。直接+20000感觉好粗暴……

**Comment by huxuan** [comment]
按照bid、tid的优先级排序依次编号，没必要搞那么复杂。

**Comment by zhzhzoo** [comment]
嗯按优先级排序依次编号后就要保证我们完成数据库转换后就不动老数据库了，这个到时候可以保证么～

**Comment by zhzhzoo** [comment]
就这么定了，按 bid tid 优先级排序～
