### ISSUE TITLE
在 repo 里的文件里记录数据库的变化

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/CAPUHome-API#9]
嗯主要是现在的 repo 里的东西没有办法反应数据库的变化，这样
- 如果某个修改需要改数据库结构的话需要人肉通知鹳狸猿把结构改成了什么样子，
- 一个新来的人类不能方便地建立数据库结构 

所以我们希望 repo 里的文件能够使得
- 鹳狸猿通过它（们）能够适当地修改服务器上的数据库结构，如果某个修改需要修改数据库结构
- 新来的人类通过它（们）可以建立能够工作的数据库结构

**Comment by huxuan** [comment]
Please be more specific. Migration can mean database migration, website migration, client migration.

**Comment by zhzhzoo** [comment]
啊谢谢提醒～已改

**Comment by huxuan** [comment]
If you mean database, I think maybe it's duplicate with #6 .

**Comment by zhzhzoo** [comment]
#6 concerns only database of module forum, but this issue covers whole database.

**Comment by huxuan** [comment]
I don't think #6 is forum only. I don't think there is any difference between these two. Closed.

**Comment by huxuan** [comment]
In flask, database is created by model.
